version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile.prod
    platform: linux/amd64
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/fd_tube_app
      - public-data:/fd_tube_app/public
      - tmp-data:/fd_tube_app/tmp
      - log-data:/fd_tube_app/log

  web:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    platform: linux/amd64
    volumes:
      - public-data:/fd_tube_app/public
      - tmp-data:/fd_tube_app/tmp
    ports:
      - 80:80
    tty: true

volumes:
    public-data:
    tmp-data:
    log-data:
