version: '3'
services:
  # ======ローカル環境の設定====== #
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: <%= ENV['DB_PASSWORD'] %> 
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - fd-tube-app-network
  
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/fd_tube_app
      - public-data:/fd_tube_app/public
      - tmp-data:/fd_tube_app/tmp
      - log-data:/fd_tube_app/log
    depends_on:
      - db
    networks:
      - fd-tube-app-network
  # ======ローカル環境の設定====== #

  # ======　本番環境の設定　====== #
  # app:
  #   build: .
  #   command: bundle exec puma -C config/puma.rb -e production
  #   volumes:
  #     - .:/fd_tube_app
  #     - public-data:/fd_tube_app/public
  #     - tmp-data:/fd_tube_app/tmp
  #     - log-data:/fd_tube_app/log
  #   networks:
  #     - fd-tube-app-network
  # ======　本番環境の設定　====== #

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/fd_tube_app/public
      - tmp-data:/fd_tube_app/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - fd-tube-app-network

volumes:
    public-data:
    tmp-data:
    log-data:
    db-data:

networks:
  fd-tube-app-network:
    external: true
