version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: <%= ENV['DB_PASSWORD'] %> 
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/fire
      - public-data:/fire/public
      - tmp-data:/fire/tmp
      - log-data:/fire/log
    depends_on:
      - db
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/fire/public
      - tmp-data:/fire/tmp
    ports:
      - 80:80
volumes:
    public-data:
    tmp-data:
    log-data:
    db-data:
