version: '3'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      # - .:/fd_tube_app
      # - public-data:/fd_tube_app/public
      # - tmp-data:/fd_tube_app/tmp
      # - log-data:/fd_tube_app/log

      - /app/log # persist logs
      -  ~/.ssh:/root/.ssh

    # depends_on:
    #   - db
  web:
    build:
      context: containers/nginx
    ports:
      - 80:80
    volumes_from:
      - web
    # volumes:
    #   - public-data:/fd_tube_app/public
    #   - tmp-data:/fd_tube_app/tmp
# volumes:
#     public-data:
#     tmp-data:
#     log-data:
    # db-data:
