version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0
commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
jobs:
  rspec:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Decode dotenv file
          command: echo $ENV_FILE | base64 --decode > .env

      - run:
          name: Build containers
          command: docker-compose -f docker-compose.dev.yml build

      - run:
          name: Setup containers
          command: docker-compose -f docker-compose.dev.yml up -d
      
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Start RSpec
          command: docker-compose -f docker-compose.dev.yml run rails_dev bundle exec rspec

      - run:
          name: Down containers
          command: docker-compose -f docker-compose.dev.yml down
       
workflows:
  version: 2
  nginx_deploy:
    jobs:
      - rspec
      - aws-ecr/build-and-push-image:
          requires:
            - rspec
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: containers/nginx/Dockerfile
          repo: fd_tube_app_web
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'fd-tube-app-task'
          cluster-name: 'fd-tube-cluster'
          service-name: 'fd-tube-app-service'
          container-image-name-updates: "container=nginx,tag=${CIRCLE_SHA1}"
  rails_deploy:
    jobs:
      - rspec
      - aws-ecr/build-and-push-image:
          requires:
            - rspec
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile.prod
          repo: fd_tube_app_rails
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'fd-tube-app-task'
          cluster-name: 'fd-tube-cluster'
          service-name: 'fd-tube-app-service'
          container-image-name-updates: "container=rails,tag=${CIRCLE_SHA1}"
